import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>deltadevs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          hi. we are delta devs. 
        </h1>

        <p className={styles.description}>
          <a href="mailto:social@deltadevs.xyz">hire us</a>
          <br/><br/>
          <a href="mailto:social@deltadevs.xyz">join us</a>
        </p>

      </main>
    </div>
  )
}
