import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div className="p-2">
      <Head>
        <title>deltadevs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.img
          animate={{
            opacity: 1,
          }}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          src={"/brandmark.svg"}
          className="h-48 mb-4"
        />
        <motion.p
          className="font-light text-6xl pt-5"
          animate={{
            opacity: 1,
            x: 0,
          }}
          whileHover={{ scale: 1.2 }}
          whileTap={{ scale: 0.9 }}
        >
          <span className="font-semibold">delta</span>devs
        </motion.p>

        <p className={"text-2xl text-center p-5 mt-12"}>
          <a
            className="text-blue-500 hover:text-blue-600"
            href="https://noble.xyz"
          >
            building noble
          </a>
          <br />
          <br />
          <a
            className="text-blue-500 hover:text-blue-600"
            href="https://x.com/deltadevs_"
          >
            follow us
          </a>
        </p>
      </main>
    </div>
  );
}
